# Generated by Django 3.2.20 on 2023-07-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230722_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/images/default.jpg', upload_to='blog/'),
        ),
    ]
